sudo: required

services:
  - docker

before_install:
  docker build -t ngbaophuc/fibonaci -f ./client/dev.Dockerfile ./client

script:
  - docker run ngbaophuc/fibonaci npm test -- --coverage

after_success:
  - docker build -t ngbaophuc/fibonaci-client -f prod.Dockerfile ./client
  - docker build -t ngbaophuc/fibonaci-nginx -f prod.Dockerfile ./nginx
  - docker build -t ngbaophuc/fibonaci-server -f prod.Dockerfile ./server
  - docker build -t ngbaophuc/fibonaci-worker -f prod.Dockerfile ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push fibonaci-client
  - docker push fibonaci-nginx
  - docker push fibonaci-server
  - docker push fibonaci-worker