sudo: required

services:
  - docker

before_install:
  docker build -t ngbaophuc/fibonaci -f ./client/dev.Dockerfile ./client

script:
  - docker run ngbaophuc/fibonaci npm test -- --coverage

after_success:
  - docker build -t ngbaophuc/fibonaci-client -f ./client/prod.Dockerfile ./client
  - docker build -t ngbaophuc/fibonaci-nginx -f ./nginx/prod.Dockerfile ./nginx
  - docker build -t ngbaophuc/fibonaci-server -f ./server/prod.Dockerfile ./server
  - docker build -t ngbaophuc/fibonaci-worker -f ./worker/prod.Dockerfile ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ngbaophuc/fibonaci-client
  - docker push ngbaophuc/fibonaci-nginx
  - docker push ngbaophuc/fibonaci-server
  - docker push ngbaophuc/fibonaci-worker